root: true
env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  accessor-pairs: error
  array-bracket-spacing: 'off'
  array-callback-return: error
  arrow-body-style: error
  arrow-parens: 'off'
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  brace-style: error
  callback-return: error
  camelcase: error
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing: error
  consistent-return: error
  consistent-this: error
  curly: error
  default-case: error
  dot-location: error
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-names: error
  func-style: 'off'
  generator-star-spacing: error
  global-require: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length:
    - error
    - exceptions: [i, k]
  id-match: error
  indent:
    - error
    - 2
  init-declarations: error
  jsx-quotes: error
  key-spacing:
    - error
    - afterColon: true
      mode: minimum
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  max-depth: error
  max-len: error
  max-nested-callbacks: error
  max-params: error
  max-statements:
    - error
    - 20
  max-statements-per-line: error
  new-cap: error
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: error
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-continue: error
  comma-dangle:
    - error
    - only-multiline
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers:
    - warn
    - ignore:
        - 0
        - 1
  no-mixed-requires: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-plusplus: error
  no-process-env: 'off'
  no-process-exit: error
  no-proto: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces:
    - error
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-expressions: error
  no-unused-vars: warn
  no-use-before-define:
    - error
    - functions: false
      classes: false
  no-useless-call: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-var: error
  no-void: error
  no-warning-comments: warn
  no-whitespace-before-property: error
  no-with: error
  object-curly-spacing:
    - error
    - always
  object-shorthand: error
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: 'off'
  prefer-arrow-callback: error
  prefer-const: 'off'
  prefer-reflect: 'off'
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: 'off'
  quotes:
    - error
    - single
  radix: error
  require-jsdoc: 'off'
  require-yield: error
  semi: error
  semi-spacing: error
  sort-imports: error
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  strict: error
  template-curly-spacing: error
  valid-jsdoc: error
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
